name: chap9rag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - faiss-cpu=1.7.4
  - pandas
  - fastapi
  - pip
  - pip:
      - langchain>=0.2.0
      - langchain-community>=0.2.0
      - langchain-mistralai
      - langchain-text-splitters
      - sentence-transformers
      - mistralai>=2.0.0        # pip uniquement, plus dans conda
      - instructor>=1.3.0
      - python-dotenv
      - ragas
      - datasets
      - uvicorn